# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyze_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analyze_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61nalyze_service.proto\x12\x0f\x61nalyze_service\"#\n\x0e\x41nalyzeRequest\x12\x11\n\tseries_id\x18\x01 \x01(\t\"\x13\n\x11\x41nalyzeAllRequest\"5\n\x0f\x41nalyzeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\tseries_id\x18\x02 \x01(\t2\xc4\x01\n\x0e\x41nalyzeService\x12U\n\x10\x41nalyzeDicomData\x12\x1f.analyze_service.AnalyzeRequest\x1a .analyze_service.AnalyzeResponse\x12[\n\x13\x41nalyzeAllDicomData\x12\".analyze_service.AnalyzeAllRequest\x1a .analyze_service.AnalyzeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyze_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEREQUEST']._serialized_start=42
  _globals['_ANALYZEREQUEST']._serialized_end=77
  _globals['_ANALYZEALLREQUEST']._serialized_start=79
  _globals['_ANALYZEALLREQUEST']._serialized_end=98
  _globals['_ANALYZERESPONSE']._serialized_start=100
  _globals['_ANALYZERESPONSE']._serialized_end=153
  _globals['_ANALYZESERVICE']._serialized_start=156
  _globals['_ANALYZESERVICE']._serialized_end=352
# @@protoc_insertion_point(module_scope)
