# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyze_all_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'analyze_all_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x61nalyze_all_service.proto\x12\x13\x61nalyze_all_service\"\x13\n\x11\x41nalyzeAllRequest\"%\n\x12\x41nalyzeAllResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2r\n\x11\x41nalyzeAllService\x12]\n\nAnalyzeAll\x12&.analyze_all_service.AnalyzeAllRequest\x1a\'.analyze_all_service.AnalyzeAllResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analyze_all_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYZEALLREQUEST']._serialized_start=50
  _globals['_ANALYZEALLREQUEST']._serialized_end=69
  _globals['_ANALYZEALLRESPONSE']._serialized_start=71
  _globals['_ANALYZEALLRESPONSE']._serialized_end=108
  _globals['_ANALYZEALLSERVICE']._serialized_start=110
  _globals['_ANALYZEALLSERVICE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
