# Generated by Django 5.1 on 2024-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ultrasound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_depth', models.FloatField()),
                ('u_cov', models.FloatField()),
                ('u_skew', models.FloatField()),
                ('stationname', models.CharField(max_length=255)),
                ('institutionname', models.CharField(max_length=255)),
                ('institutionaldepartmentname', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('modality', models.CharField(max_length=255)),
                ('instance', models.CharField(max_length=255)),
                ('seriesdate', models.DateField()),
            ],
            options={
                'db_table': 'ultrasound',
            },
        ),
    ]
